# Generated by Django 5.2 on 2025-04-17 14:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('company_name', models.CharField(max_length=100)),
                ('salary', models.IntegerField()),
                ('place', models.CharField(max_length=100)),
                ('timing', models.CharField(choices=[('9 AM to 5 PM', '9 AM to 5 PM'), ('10 AM to 4 PM', '10 AM to 4 PM'), ('10 AM to 12 PM', '10 AM to 12 PM'), ('2 PM to 8 PM', '2 PM to 8 PM')], max_length=50)),
                ('apply_link', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='jobPost/')),
                ('deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
