# Generated by Django 5.1.5 on 2025-04-24 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobopportunities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobpost',
            name='timing',
        ),
        migrations.AddField(
            model_name='jobpost',
            name='end_timing',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='start_timing',
            field=models.TimeField(blank=True, max_length=50, null=True),
        ),
    ]
