# Generated by Django 5.1.5 on 2025-04-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='profiles/'),
        ),
    ]
