# Generated by Django 5.1.5 on 2025-05-05 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_alter_userprofile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='instragram_link',
            new_name='instagram_link',
        ),
    ]
