# Generated by Django 5.1.5 on 2025-05-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_rename_instragram_link_userprofile_instagram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='blood_grp',
            field=models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=15, null=True),
        ),
    ]
