# Generated by Django 5.1.5 on 2025-05-04 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upcomingevents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='upcomingevent',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
